(()=>{
"use strict";
const $=id=>document.getElementById(id);
const client=window.supabase?.createClient("https://mjsoffmcekzhenuyfzud.supabase.co",window.DALE_SUPABASE_KEY);
const login=$("daleLogin"),dashboard=$("daleDashboard"),notice=$("adminNotice");
const show=(s,e=false)=>{notice.textContent=s;notice.style.color=e?"#e88":"#BD8D64"};
const now=new Date(),day=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
let current=null;
const time=h=>(h%12||12)+":00 "+(h<12?"AM":"PM");
function card(b){const n=document.createElement("article");n.className="admin-card";const head=document.createElement("h3");head.textContent=b.full_name+" · "+b.status.toUpperCase();const detail=document.createElement("p");detail.textContent=String(b.session_date)+" · "+time(b.start_hour)+" – "+time(b.end_hour)+" · "+b.player_count+" player(s) · ₱"+Number(b.quoted_total).toLocaleString("en-PH");const contact=document.createElement("p");contact.textContent="Contact: "+b.contact+" | Court: "+b.court+" | Goal: "+b.goal;n.append(head,detail,contact);if(b.status==="pending"){for(const action of ["confirmed","rejected"]){const btn=document.createElement("button");btn.textContent=action==="confirmed"?"Confirm booking":"Reject request";btn.onclick=async()=>{btn.disabled=true;try{const {error}=await client.from("dale_booking_requests").update({status:action}).eq("id",b.id).eq("status","pending");if(error)throw error;show("Request "+action+".");await refresh()}catch(err){show("Unable to "+action+". Hours may already be reserved. Refresh and retry.",true);btn.disabled=false}};n.append(btn)}}if(b.status==="confirmed"){const btn=document.createElement("button");btn.textContent="Cancel booking";btn.onclick=async()=>{if(!confirm("Cancel this confirmed booking?"))return;const {error}=await client.from("dale_booking_requests").update({status:"cancelled"}).eq("id",b.id);if(error)show("Cancellation failed.",true);else await refresh()};n.append(btn)}return n}
async function refresh(){if(!client)return;const {data,error}=await client.from("dale_booking_requests").select("*").order("session_date",{ascending:true}).order("start_hour",{ascending:true});if(error){show("Cannot load requests: "+error.message,true);return;}const wrap=$("requestList");wrap.replaceChildren(...(data||[]).map(card));if(!data?.length)wrap.textContent="No booking requests yet.";const v=await client.from("dale_unavailable_hours").select("session_date,hour,reason").gte("session_date",day(now)).order("session_date").order("hour").limit(500);const locks=$("lockedHours");locks.replaceChildren();for(const x of v.data||[]){const e=document.createElement("div");e.textContent=x.session_date+" · "+time(x.hour)+" · "+x.reason;locks.appendChild(e)}}
async function updateAuth(){const {data}=await client.auth.getSession();current=data?.session||null;if(!current){login.hidden=false;dashboard.hidden=true;return;}const {data:admin,error}=await client.from("dale_admin_users").select("user_id").eq("user_id",current.user.id).maybeSingle();if(error||!admin){await client.auth.signOut();login.hidden=false;dashboard.hidden=true;show("Account is not authorized as Coach Dale administrator.",true);return;}login.hidden=true;dashboard.hidden=false;show("Signed in as "+current.user.email);await refresh()}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();if(!client)return;show("Signing in…");const {error}=await client.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});if(error){show("Login failed. Check credentials.",true);return;}await updateAuth()});
$("logoutBtn").addEventListener("click",async()=>{await client.auth.signOut();await updateAuth()});
$("refreshAdmin").addEventListener("click",refresh);
if(!client){show("Supabase client could not start.",true)}else updateAuth();
})();