(()=>{"use strict";
const $=id=>document.getElementById(id),db=window.supabase?.createClient("https://mjsoffmcekzhenuyfzud.supabase.co",window.DALE_SUPABASE_KEY);
const login=$("daleLogin"),dash=$("daleDashboard"),notice=$("adminNotice");
let bookings=[],locks=[],authorized=false,expanded=false,filter="active",busy=false;
const localDate=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const time=h=>(h%12||12)+":00 "+(h<12?"AM":"PM");
const phpHour=()=>Number(new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Manila",hour:"2-digit",hourCycle:"h23"}).format(new Date()));
const peso=n=>"₱"+Number(n).toLocaleString("en-PH");
const el=(tag,cls,txt)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(txt!==undefined)x.textContent=txt;return x};
function msg(s,bad=false){notice.textContent=s;notice.style.color=bad?"#FFA39A":"#E7C199"}
function enableForm(flag){for(const b of document.querySelectorAll("#daleDashboard button"))b.disabled=!flag;}
function sameDateSlot(d,h){return d===today()&&h<=phpHour();}
function renderStats(){const active=bookings.filter(x=>x.status==="confirmed"&&x.session_date>=today());const pending=bookings.filter(x=>x.status==="pending"&&x.session_date>=today());const past=bookings.filter(x=>x.session_date<today());const stats=[pending.length,active.length,locks.filter(x=>x.reason==="blocked"&&x.session_date>=today()).length,past.length];["statPending","statConfirmed","statBlocked","statPast"].forEach((id,i)=>$(id).textContent=stats[i]);}
function actions(item,n){const tool=el("div","admin-action-row");for(const kind of (item.status==="confirmed"?["edit","payment","confirmation","complete"]:["edit","payment","confirmation"])){const b=el("button","",kind==="edit"?"Edit Booking":kind==="payment"?"Record Payment":kind==="complete"?"Mark Completed":"Confirmation");b.type="button";b.onclick=()=>window.DaleOps?.open(kind,item);tool.append(b)}n.append(tool);if(item.status==="pending"&&item.session_date>=today()){const bar=el("div","admin-action-row");for(const a of ["confirmed","rejected"]){const btn=el("button",a==="rejected"?"reject":"",a==="confirmed"?"Confirm booking":"Reject request");btn.type="button";btn.onclick=()=>changeStatus(item,a);bar.append(btn)}n.append(bar)}else if(item.status==="confirmed"){const bar=el("div","admin-action-row");const btn=el("button","cancel","Cancel booking");btn.type="button";btn.onclick=()=>{if(confirm("Cancel this confirmed booking and release its reserved hours?"))changeStatus(item,"cancelled")};bar.append(btn);n.append(bar)}}
function card(b){const n=el("article","admin-card");n.dataset.bookingId=b.id;const head=el("div","admin-card-title");head.append(el("h3","",b.full_name),el("span","admin-status "+b.status,b.status));n.append(head);n.append(el("p","admin-booking-time",b.session_date+" · "+time(b.start_hour)+" – "+time(b.end_hour)+" · "+(b.end_hour-b.start_hour)+" hour(s)"));n.append(el("p","",b.player_count+" player(s) · "+peso(b.quoted_total)+" · "+b.court));n.append(el("p","","Contact: "+b.contact+" · Goal: "+b.goal));actions(b,n);return n}
function renderRequests(){const query=$("requestSearch").value.trim().toLowerCase();const selected=bookings.filter(b=>{const match=(!query||[b.full_name,b.contact,b.court].some(z=>String(z||"").toLowerCase().includes(query)));if(!match)return false;if(filter==="pending")return b.status==="pending"&&b.session_date>=today();if(filter==="confirmed")return b.status==="confirmed"&&b.session_date>=today();if(filter==="past")return b.session_date<today();if(filter==="closed")return b.status==="cancelled"||b.status==="rejected";return b.session_date>=today()&&(b.status==="pending"||b.status==="confirmed")});selected.sort((a,b)=>a.session_date.localeCompare(b.session_date)||a.start_hour-b.start_hour);const shown=expanded?selected:selected.slice(0,3),wrap=$("requestList");wrap.replaceChildren(...shown.map(card));if(!selected.length)wrap.append(el("div","admin-empty","No matching bookings. New customer requests will show here."));const more=$("showAllRequests");more.hidden=selected.length<=3;more.textContent=expanded?"Show less":"Show all ("+selected.length+")";}
function renderLocks(){const date=$("blockDate").value,wrap=$("lockedHours");const onDate=locks.filter(z=>z.session_date===date).sort((a,b)=>a.hour-b.hour);wrap.replaceChildren();if(!onDate.length)wrap.append(el("div","admin-empty","No blocked or reserved hours on this date."));for(const b of onDate){const n=el("div","admin-locked "+b.reason);const info=el("div");info.append(el("strong","",time(b.hour)+" – "+time(b.hour+1)),el("small","",b.reason==="blocked"?"Manually blocked":"Confirmed booking"));n.append(info);if(b.reason==="blocked"){const button=el("button","","Unblock");button.type="button";button.onclick=()=>unblock(b,button);n.append(button)}else n.append(el("span","admin-lock-pill","Reserved"));wrap.append(n)}}
async function refresh(){if(!authorized||!db)return;const [a,b]=await Promise.all([db.from("dale_booking_requests").select("*").order("session_date",{ascending:true}).order("start_hour",{ascending:true}).limit(1000),db.from("dale_unavailable_hours").select("session_date,hour,reason").gte("session_date",today()).order("session_date").order("hour").limit(1500)]);if(a.error||b.error){msg("Unable to load bookings or blocked hours: "+(a.error?.message||b.error?.message),true);return}bookings=a.data||[];locks=b.data||[];window.DaleOps?.sync(bookings,locks);renderStats();renderRequests();renderLocks()}
async function changeStatus(b,status){if(busy)return;busy=true;enableForm(false);msg("Saving booking status…");try{const r=await db.from("dale_booking_requests").update({status}).eq("id",b.id).eq("status",b.status).select("id,status");if(r.error)throw r.error;if(r.data?.length!==1)throw Error("Booking was changed by another session. Refresh.");await refresh();msg(status==="confirmed"?"Booking confirmed; its hours are reserved.":status==="cancelled"?"Booking cancelled; its hours are released.":"Booking request rejected.")}catch(e){msg("Could not update booking: "+e.message,true);await refresh()}finally{busy=false;enableForm(true)}}
async function unblock(item,button){if(busy)return;if(!confirm("Make "+time(item.hour)+" – "+time(item.hour+1)+" available again?"))return;busy=true;button.disabled=true;msg("Unblocking hour…");const res=await db.from("dale_unavailable_hours").delete().eq("session_date",item.session_date).eq("hour",item.hour).eq("reason","blocked").select("session_date,hour");if(res.error||res.data?.length!==1)msg("Could not unblock hour. Refresh and try again.",true);else msg("Hour is available for booking again.");busy=false;await refresh()}
async function blockHours(ev){ev.preventDefault();if(busy)return;const d=$("blockDate").value,from=Number($("blockStart").value),to=Number($("blockEnd").value),note=$("blockNote").value.trim();const state=$("blockStatus");if(!d||d<today()||from<10||to>22||from>=to||to-from>12||(d===today()&&from<=phpHour())){state.textContent="Choose a future date and valid hours between 10 AM and 10 PM.";return}const occupied=locks.filter(b=>b.session_date===d&&b.hour>=from&&b.hour<to);if(occupied.length){state.textContent="This range includes an already blocked or confirmed hour. Choose available hours.";return}const rows=Array.from({length:to-from},(_,i)=>({session_date:d,hour:from+i,reason:"blocked",note:note.slice(0,200)}));busy=true;enableForm(false);state.textContent="Blocking hours…";const result=await db.from("dale_unavailable_hours").insert(rows);if(result.error){state.textContent="Unable to block hours. Please refresh and try again.";msg("Schedule conflict: "+result.error.message,true)}else{state.textContent=time(from)+" – "+time(to)+" marked unavailable.";msg("Schedule blocked successfully.")}busy=false;enableForm(true);await refresh()}
async function auth(){if(!db){msg("Booking service unavailable.",true);return}const {data}=await db.auth.getSession(),session=data?.session;if(!session){authorized=false;window.DaleOps?.setAuthorized(false);login.hidden=false;dash.hidden=true;return}const {data:admin,error}=await db.from("dale_admin_users").select("user_id").eq("user_id",session.user.id).maybeSingle();if(error||!admin){await db.auth.signOut();authorized=false;login.hidden=false;dash.hidden=true;msg("This account is not authorized to manage Coach Dale's bookings.",true);return}authorized=true;login.hidden=true;dash.hidden=false;msg("Signed in as "+session.user.email);await refresh();window.DaleOps?.setAuthorized(true)}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();if(!db)return;msg("Signing in…");const {error}=await db.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});if(error){msg("Sign-in failed. Check your credentials.",true);return}await auth()});
$("logoutBtn").onclick=async()=>{await db.auth.signOut();await auth()};$("refreshAdmin").onclick=refresh;
$("blockForm").addEventListener("submit",blockHours);$("blockDate").addEventListener("change",renderLocks);
$("requestFilter").addEventListener("change",v=>{filter=v.target.value;expanded=false;renderRequests()});$("requestSearch").addEventListener("input",()=>{expanded=false;renderRequests()});$("showAllRequests").addEventListener("click",()=>{expanded=!expanded;renderRequests()});
$("blockDate").min=today();$("blockDate").value=today();
for(const id of ["blockStart","blockEnd"]){const select=$(id);for(let h=10;h<=(id==="blockStart"?21:22);h++){const op=document.createElement("option");op.value=h;op.textContent=time(h);select.append(op)}}$("blockStart").value="10";$("blockEnd").value="11";
if(!db)msg("Unable to load Supabase client.",true);else auth();
})();