(()=>{
"use strict";
const url="https://mjsoffmcekzhenuyfzud.supabase.co",key="sb_publishable_2I-ZQ7mAxp8mDSftamqgSw_dHTmHZbs";
const sb=window.supabase?.createClient(url,key);
const $=id=>document.getElementById(id),hours=[10,11,12,13,14,15,16,17,18,19,20,21];
const date=$("daleDate"), slots=$("daleHours"), status=$("daleBookingStatus"),send=$("daleSubmit"),name=$("daleName"),contact=$("daleContact"),players=$("dalePlayers"),goal=$("daleGoal"),court=$("daleCourt"),summary=$("daleBookingSummary");
let chosen=[],unavailable=new Set(),loading=false;
const dateKey=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
const pretty=h=>((h+11)%12+1)+":00 "+(h<12?"AM":"PM");
const total=()=>chosen.length*(1000+(Number(players.value)-1)*350);
function message(s,error=false){status.textContent=s;status.style.color=error?"#B64239":"#173F35"}
function selectedRange(){const a=[...chosen].sort((a,b)=>a-b);return a.length?[a[0],a[a.length-1]+1]:null}
function update(){const r=selectedRange();summary.textContent=r?"₱"+total().toLocaleString("en-PH")+" · "+pretty(r[0])+" – "+pretty(r[1])+" · "+chosen.length+" hour(s) · "+players.value+" player(s)":"Select consecutive available hours.";send.disabled=!sb||loading||!r;}
function render(){slots.innerHTML="";for(const h of hours){const b=document.createElement("button");b.type="button";b.className="dale-slot";b.textContent=pretty(h);const occupied=unavailable.has(h)||date.value===dateKey(new Date())&&h<=new Date().getHours();b.disabled=occupied;b.setAttribute("aria-pressed",String(chosen.includes(h)));if(chosen.includes(h))b.classList.add("selected");if(occupied)b.classList.add("unavailable");b.onclick=()=>{const next=chosen.includes(h)?chosen.filter(x=>x!==h):[...chosen,h].sort((a,b)=>a-b);if(next.length&&next[next.length-1]-next[0]+1!==next.length){message("Only consecutive hours can be selected.",true);return}chosen=next;render();message("Choose players and complete the form.");};slots.appendChild(b)}update()}
async function refresh(preserveMessage=false){if(!sb){message("Booking service is unavailable. Please try again later.",true);return;}chosen=[];unavailable=new Set();loading=true;update();message("Checking live availability…");try{const {data,error}=await sb.from("dale_unavailable_hours").select("hour,reason").eq("session_date",date.value);if(error)throw error;unavailable=new Set((data||[]).map(x=>Number(x.hour)));if(!preserveMessage)message("Live availability loaded. Tap consecutive hours.");}catch(e){message("Unable to load availability. Please refresh.",true);unavailable=new Set(hours)}finally{loading=false;render()}}
date.min=dateKey(new Date());date.max=dateKey(new Date(Date.now()+180*86400000));date.value=date.min;
date.addEventListener("change",refresh);players.addEventListener("change",update);$("daleRefresh").addEventListener("click",refresh);
$("daleForm").addEventListener("submit",async e=>{e.preventDefault();const r=selectedRange();if(!r||loading||!sb)return;const n=name.value.trim(),c=contact.value.trim();if(n.length<2||c.length<5){message("Enter your name and contact details.",true);return;}loading=true;update();message("Sending booking request…");try{const {error}=await sb.from("dale_booking_requests").insert({full_name:n,contact:c,session_date:date.value,start_hour:r[0],end_hour:r[1],player_count:Number(players.value),court:court.value,goal:goal.value});if(error)throw error;chosen=[];render();message("Booking request submitted! The schedule is not confirmed until approved by Coach Dale.");contact.value="";}catch(err){message(/duplicate key/i.test(err.message||"")?"You already have a pending request for those hours.":(/available|conflict|passed/i.test(err.message||"")?"Selected hours are no longer available. Refresh the schedule.":"Request could not be sent. Please try again."),true)}finally{loading=false;await refresh(true);}});
refresh();
})();